/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsListPageRouteImport } from './routes/news.list.$page'
import { Route as NewsPostSlugRouteImport } from './routes/news.post.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsListPageRoute = NewsListPageRouteImport.update({
  id: '/news/list/$page',
  path: '/news/list/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsPostSlugRoute = NewsPostSlugRouteImport.update({
  id: '/news/post/$slug',
  path: '/news/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news/list/$page': typeof NewsListPageRoute
  '/news/post/$slug': typeof NewsPostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news/list/$page': typeof NewsListPageRoute
  '/news/post/$slug': typeof NewsPostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news/list/$page': typeof NewsListPageRoute
  '/news/post/$slug': typeof NewsPostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news/list/$page' | '/news/post/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news/list/$page' | '/news/post/$slug'
  id: '__root__' | '/' | '/news/list/$page' | '/news/post/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsListPageRoute: typeof NewsListPageRoute
  NewsPostSlugRoute: typeof NewsPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/list/$page': {
      id: '/news/list/$page'
      path: '/news/list/$page'
      fullPath: '/news/list/$page'
      preLoaderRoute: typeof NewsListPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/post/$slug': {
      id: '/news/post/$slug'
      path: '/news/post/$slug'
      fullPath: '/news/post/$slug'
      preLoaderRoute: typeof NewsPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsListPageRoute: NewsListPageRoute,
  NewsPostSlugRoute: NewsPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
